# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-linux:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: mrpossoms/g.h-ci
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Get deps"
          command: "gitman install"
      - run:
          name: "Congif g.h"
          command: "mkdir build && cd build && cmake -DG_BUILD_TESTS=1 -DG_BUILD_EXAMPLES=1 .."
      - run:
          name: "Build g.h"
          command: "make -j"
  build-mac:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: "Build"
          command: "mkdir build && cd build && cmake -DG_BUILD_TESTS=1 -DG_BUILD_EXAMPLES=1 .."
  
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build-linux
      - build-mac

